DROP DATABASE IF EXISTS AsiaBarRestaurant;

-- Luego la creamos
CREATE DATABASE AsiaBarRestaurant;

-- Seleccionamos la base de datos
USE AsiaBarRestaurant;

CREATE TABLE Users (
    Username VARCHAR(25) PRIMARY KEY NOT NULL,
    Type VARCHAR(25) NOT NULL,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE Clients (
    IdDocument VARCHAR(20) PRIMARY KEY NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Address VARCHAR(25) NOT NULL,
    Phone VARCHAR(20) NOT NULL
);

CREATE TABLE MainDish (
    Name VARCHAR(50) PRIMARY KEY NOT NULL,
    Availability INT DEFAULT TRUE NOT NULL,
    Price FLOAT NOT NULL,
    Description VARCHAR(100)
);

CREATE TABLE SideDish (
    Name VARCHAR(50) PRIMARY KEY NOT NULL,
    Availability INT DEFAULT TRUE NOT NULL,
    Price FLOAT NOT NULL,
    Description VARCHAR(100)
);

CREATE TABLE Product (
    Name VARCHAR(50) PRIMARY KEY NOT NULL,
    Availability INT DEFAULT TRUE NOT NULL,
    Price FLOAT NOT NULL,
    Description VARCHAR(100)
);

CREATE TABLE Sales (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ClientIdDocument VARCHAR(20) NOT NULL,
    ClientName VARCHAR(50) NOT NULL,
    Type VARCHAR(20) NOT NULL,
    DeliverymanName VARCHAR(50),
    Note TEXT,
    Direction VARCHAR(100),
    TableNumber VARCHAR(20)
);

CREATE TABLE SaleDetails (
    ID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Price FLOAT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (ID) REFERENCES Sales(ID) ON DELETE CASCADE
);

CREATE TABLE Deliverymen (
    Name VARCHAR(50) PRIMARY KEY NOT NULL,
    Area VARCHAR(25) NOT NULL,
    Availability INT DEFAULT TRUE NOT NULL,
    Phone VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS TipoCambio (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Tasa DECIMAL(10, 4) NOT NULL,
    FechaActualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO TipoCambio (Tasa) VALUES (212.48);